### ISSUE TITLE
Unable to execute Terrascan

### ISSUE THREAD

**Issue by kassyuz** [cesar-rodriguez/terrascan#170]
* terrascan version: latest
* Python version: 2.6.9
* Operating System: Docker Image `cwill747/alpine-python2.` 

### Description
I am trying to run Terrascan but I am getting a dependency error output

### What I Did
The volume mapped was pointing to a Terraform project (I run the container inside this directory) with these files:
```
-rw-r--r--    1 1000     1000           813 Jul  5 20:12 README.md
-rw-r--r--    1 1000     1000           885 Jul 12 16:50 main.tf
-rw-r--r--    1 1000     1000           410 Jul  5 20:12 outputs.tf
-rw-r--r--    1 1000     1000          2554 Jul 11 22:38 terraform.plan
-rw-r--r--    1 1000     1000           298 Jul  5 20:12 vars.tf
```

First I started a docker container:
```
$ docker run  -it   -v $(pwd):/data cwill747/alpine-python2.6  /bin/sh 
```

Then I installed Terrascan as described at the documentation (README.md):
```
$ pip install terrascan
```

Run the scan
```
terrascan -location /data --test all
```

## Output log
```
/data # terrascan -location /data --test all
Traceback (most recent call last):
  File "/usr/bin/terrascan", line 7, in <module>
    from terrascan.__main__ import main
  File "/usr/lib/python2.6/site-packages/terrascan/__main__.py", line 5, in <module>
    from .terrascan import main
  File "/usr/lib/python2.6/site-packages/terrascan/terrascan.py", line 10, in <module>
    from terrascan.checks.security_group import TestSecurityGroups
ImportError: No module named checks.security_group

```

**Comment by bryanhuntesl** [comment]
Any idea ? I've got the same issue.

**Comment by kassyuz** [comment]
Hi @bryanhuntesl, not yet but I checked and there are a bunch of PRs opened regarding lib updates, maybe some of them fix this issue.

Unfortunately, I had to remove the _terrascan_ step from my CI pipeline.

**Comment by cesar-rodriguez** [comment]
I've updated all dependencies to the latest version and issues and new release v0.1.1. Hopefully this fixes the issues you were having.

**Comment by cesar-rodriguez** [comment]
This issue should be addressed in the latest release.
