### ISSUE TITLE
it doesn't work on tf 0.12

### ISSUE THREAD

**Issue by mahgblack** [cesar-rodriguez/terrascan#181]
* terrascan version:
* Python version:
* Operating System:

### Description

it doen't work on terraform 0.12 syntax

### What I Did
terrascan --location . --tests security_group 
error: SyntaxError: Unexpected identi

**Comment by liamg** [comment]
Until this is fixed you can try https://github.com/liamg/tfsec - I've just had to support the 0.12 (HCL 2.0) upgrade there.

**Comment by schosterbarak** [comment]
Until this is fixed you can also try https://github.com/bridgecrewio/checkov - supports 0.12 and above

**Comment by cesar-rodriguez** [comment]
There's a PR open to address this #150. Hoping to merge that soon.

**Comment by cesar-rodriguez** [comment]
This has been addressed in the [v0.2.0](https://github.com/cesar-rodriguez/terrascan/releases/tag/v0.2.0) release.
