### ISSUE TITLE
Bump `pyhcl` version dependency

### ISSUE THREAD

**Issue by yermulnik** [cesar-rodriguez/terrascan#232]
* terrascan version: 0.2.0
* Python version: 3.6.10
* Operating System: Linux Mint 18.3 Sylvia x86_64

### Description

```
ERROR: terrascan 0.2.0 has requirement pyhcl==0.4.0, but you'll have pyhcl 0.4.4 which is incompatible.
```

### What I Did

```
pip3.6 --no-cache-dir install --upgrade terrascan
```

**Comment by cesar-rodriguez** [comment]
Thanks for opening this issue. This has been fixed in version 0.2.1.
