### ISSUE TITLE
Proposal: Create a terrascan wrapper with argument validation

### ISSUE THREAD

**Issue by jason-tyler** [cesar-rodriguez/terrascan#5]
Use a wrapper to allow clients to invoke Terrascan with arguments. 

Example: https://github.com/jason-tyler/terrascan/tree/feature/main_args

If you agree with this method, create a "feature/main_args" branch and I'll PR a start at this into your repo.

**Comment by cesar-rodriguez** [comment]
Definitely. I thought of doing this eventually, but didn't had time to get to it. What I like about this is that we can swap out the dependency on python unittest at some point without affecting the way you execute terrascan.

**Comment by jason-tyler** [comment]
Good point. I'll submit a PR after you create the 'feature/main_args' branch in your repo.

**Comment by cesar-rodriguez** [comment]
Done
